# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      prNum:
        description: 'Pr number'
        required: true
        default: '731'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - id: exists
        run: echo ::set-output name=status_code::$(curl -o /dev/null -s -k -w "%{http_code}\n" https://pr-${{ github.event.inputs.prNum }}.preview.sledilnik.org)
  # This workflow contains a single job called "build"
  build:
    needs: [check]
    if: needs.check.outputs.status_code != '404'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
